apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: volsync-product
  namespace: openshift-operators
spec:
  channel: stable
  installPlanApproval: Automatic
  name: volsync-product
  source: redhat-operators
  sourceNamespace: openshift-marketplace
